FROM node:10.16.2-stretch-slim

WORKDIR /usr/src/app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY package*.json ./
RUN npm prune && npm install

COPY . .

CMD [ "npm", "run", "start:prod" ]