---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-server-service"
  namespace: "default"
  labels:
    app: "web-server"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "web-server"
  type: "ClusterIP"
