---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "twtr-backend"
  namespace: "default"
  labels:
    app: "twtr-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "twtr-backend"
  template:
    metadata:
      labels:
        app: "twtr-backend"
    spec:
      containers:
      - name: "production-web-server-sha256"
        image: "us.gcr.io/twtr-backend/production-web-server@sha256:accb44b11a13bc840afd547b1e093300e7350880de3a02a796f8f93d81982462"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "twtr-backend-hpa"
  namespace: "default"
  labels:
    app: "twtr-backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "twtr-backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
